services:
  postgres:
    container_name: db_go_batch
    image: postgres:cust
    environment:
      POSTGRES_USER: ${DB_USER:-test}
      POSTGRES_PASSWORD: ${DB_PASS:-123456}  # Usa variable de entorno
      #POSTGRES_DB: app_db
      PGDATA: /var/lib/postgresql/data/pgdata  # Optimización para volumenes
      # Configuraciones de performance (ajustables según tu HW):
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen persistente
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro  # Config personalizada (opcional)
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d app_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    network_mode: host

volumes:
  postgres_data:
